---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: replayweb-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/yourusername/replayweb-infrastructure  # Replace with your infrastructure repo URL