---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: replayweb-staging
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/overlays/staging"
  prune: true
  sourceRef:
    kind: GitRepository
    name: replayweb-infrastructure
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: staging-replayweb-page
      namespace: replayweb
  timeout: 5m