apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: replayweb-page-base

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: replayweb-page
  app.kubernetes.io/version: "2.3.16"
  app.kubernetes.io/managed-by: flux

images:
- name: replayweb-page
  newTag: latest