apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-loadbalancer
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  annotations:
    # Azure Load Balancer annotations
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "replayweb-test_group"
    service.beta.kubernetes.io/azure-pip-name: "libutk-public-ip"  # We'll create this next
    service.beta.kubernetes.io/azure-dns-label-name: "libutk"  # Optional: Creates DNS label
    
    # Load balancer optimization
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
    
    # Optional: Use Standard SKU (recommended)
    service.beta.kubernetes.io/azure-load-balancer-sku: "standard"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller