apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: replayweb-page-staging

namespace: replayweb

resources:
- ../../base

patchesStrategicMerge:
- ingress-patch.yaml
- deployment-patch.yaml

namePrefix: staging-

commonLabels:
  environment: staging

images:
- name: replayweb-page
  newTag: staging-latest